#include <stdio.h>
int main() {
	printf("<AMO FAZER EXERCICIO NO URI>\n<    AMO FAZER EXERCICIO NO URI>\n<AMO FAZER EXERCICIO >\n<AMO FAZER EXERCICIO NO URI>\n<AMO FAZER EXERCICIO NO URI    >\n<AMO FAZER EXERCICIO NO URI>\n<          AMO FAZER EXERCICIO >\n<AMO FAZER EXERCICIO           >\n");
	return 0;
}
